### ISSUE TITLE
Chapter 1 Exercise 2 Beyond 1

### ISSUE THREAD

**Issue by reachtarunhere** [reuven/python-workout#3]
The code in the repo is not in line with what is stated in the book because it uses the splat character for the first argument. This leads to different behaviour from the in-built sum

> 
> In [1]: sum([1,2,3], 4)
> Out[1]: 10
> 
> In [2]: %paste
> 
> 
> def mysum(*numbers, start=0):
>     """Accepts any number of numeric arguments as inputs.
> Returns the sum of those numbers, plus the value of "start",
> which defaults to 0.
> """
>     output = start
>     for number in numbers:
>         output += number
>     return output
> 
> In [3]: mysum([1,2,3], 4)
> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> <ipython-input-3-5e8980c1a208> in <module>()
> ----> 1 mysum([1,2,3], 4)
> 
> <ipython-input-2-b6c74eea2551> in mysum(start, *numbers)
>       6     output = start
>       7     for number in numbers:
> ----> 8         output += number
>       9     return output
> 
> TypeError: unsupported operand type(s) for +=: 'int' and 'list'
>

**Comment by reuven** [comment]
You're right; I've updated the code to reflect the specification in the book.  Thanks!

**Comment by reachtarunhere** [comment]
Thanks for the update and the great book!
